# Generated by Django 4.2 on 2023-04-05 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("KIT", "Kit"),
                            ("BARRA", "Barra"),
                            ("TRUFA", "Trufa"),
                            ("EVENTO", "Evento"),
                        ],
                        default="BARRA",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
